<?php


##################################################################
#	Please change followins appropriate for your environment #
##################################################################
define ("SILENT", 		     FALSE);			//if true, no error message will be reported to the browser
define ("LOG_FATAL_ONLY",	     FALSE);			//if true, only fatal errors will be reported and logged
define ("DEFAULT_SERVER",      "localhost");	//GTCM server is running on
define ("DEFAULT_PORT",		     30000);			//port number that GTCM server is listening to
define ("LOGFILE", 	       "error.log");		//errors are logged in this file, make sure to chmod a+w
define ("DB1",		"/opt/lsb-gtm/gtm_V60001_x8664/mumps.dat");
define ("DB2",		"/opt/lsb-gtm/gtm_V60001_x8664/mumps.dat");
define ("HOST1",	       "localhost");
define ("HOST2",               "localhost");
define ("PORTNO",	             30000);

?>
